---
# tasks file for deploy_desktop
- name: Install a list of packages
  become: true
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - vim 
      - ssh
      - git
      - vagrant 
      - vlc 
      - guake 
      - g++ 
      - cmake
      - libreoffice 
      - htop 
      - nmap 
      - rename
      - aptitude
      - gparted
      - wcalc
      - python3-pip 
      - python3-virtualenv 
      - virtualenvwrapper
      - libxss1
      - libappindicator1
      - libindicator7

- name: Delete unneeded packages
  become: true
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
      - gnumeric
      - abiword

- name: Check SSH private
  stat: path=~/.ssh/id_rsa
  register: private_exists

- name: Check SSH public
  stat: path=~/.ssh/id_rsa.pub
  register: public_exists

- name: Create keypair
  shell: ssh-keygen -t rsa -b 2048 -f ~/.ssh/id_rsa -q -N ""
  when: not private_exists.stat.exists or not public_exists.stat.exists

- name: Download Google Chrome
  get_url: 
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: /tmp/google-chrome.deb

- name: Install Google Chrome
  become: true
  apt:
    deb: /tmp/google-chrome.deb

- name: Delete unneeded Google Chrome deb
  file:
    path: /tmp/google-chrome.deb
    state: absent

- name: Copy configs
  copy:
    src: .vimrc
    dest: ~/.vimrc

- name: Set git global configs
  shell: | 
         git config --global user.email "{{user_email}}" && 
         git config --global user.name "{{user_name}}"

- name: Set panel configuration
  copy:
    src: lxpanel
    dest: ~/.config/
  
